# Change these first
owner: 360psg # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: 360 PSG
    url: https://www.360psg.com
  - name: 360PSG DNS1
    check: "tcp-ping"
    url: ns1.360psg.com
    port: 53
  - name: 360PSG DNS2
    check: "tcp-ping"
    url: ns2.360psg.com
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.360psg.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 360PSG Statuses
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the 360 PSG status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.360psg.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
